
resources:
  - url: /local/custom_cards/icloud3-event-log-card.js?v=1.001
    type: js
   
title: Home
views:

#=============================================================
  - title: Main
    icon: mdi:star-outline
    cards:        
      - type: vertical-stack
        cards:
          - type: glance
            title: Status
            column_width: 25%
            entities:
              - entity: sensor.gary_iphone_badge
                name: Gary
              - entity: sensor.lillian_iphone_badge
                name: Lillian
              - entity: sensor.garage_door_badge
                name: Garage
               
      - type: map
        entities:
          - device_tracker.gary_iphone
          - device_tracker.lillian_iphone
          - zone.home
          - zone.quail
          - zone.whse
          
#=============================================================
  - title: Location (Gary)
    icon: mdi:cellphone-iphone
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Location Info - Gary
            column_width: 20%
            entities:
              - entity: device_tracker.gary_iphone
                name: Gary
              - entity: sensor.gary_iphone_interval
                name: Interval
                icon: mdi:clock-start
              - entity: sensor.gary_iphone_travel_time
                name: TravTime
                icon: mdi:clock-outline
              - entity: sensor.gary_iphone_zone_distance
                name: HomeDist
                icon: mdi:map-marker-distance 
              - entity: sensor.gary_iphone_next_update
                name: NextUpdt
                icon: mdi:update
         
          - type: glance
            column_width: 20%
            entities:
              - entity: sensor.gary_iphone_waze_distance
                name: WazeDist
                icon: mdi:map-marker-distance
              - entity: sensor.gary_iphone_calc_distance
                name: CalcDist
                icon: mdi:map-marker-distance
              - entity: sensor.gary_iphone_dir_of_travel
                name: Direction
                icon: mdi:compass-outline
              - entity: sensor.gary_iphone_last_located
                name: Located
                icon: mdi:map-clock
              - entity: sensor.gary_iphone_last_update
                name: LastUpdt
                icon: mdi:history
              
          - type: horizontal-stack
            cards:
            - type: entities
              entities:
                - entity: sensor.gary_iphone_info
                  name: Info
                  icon: mdi:information-outline 

          - type: entities
            entities:
              - script.icloud_update_location_gary
              - script.homeassistant_restart

#-------------------------------------------------------------            
      - type: vertical-stack
        cards:
          - type: glance
            title: Location Info - Lillian
            column_width: 20%
            entities:
              - entity: device_tracker.lillian_iphone
                name: Gary
              - entity: sensor.lillian_iphone_interval
                name: Interval
                icon: mdi:clock-start
              - entity: sensor.lillian_iphone_travel_time
                name: TravTime
                icon: mdi:clock-outline
              - entity: sensor.lillian_iphone_zone_distance
                name: HomeDist
                icon: mdi:map-marker-distance 
              - entity: sensor.lillian_iphone_next_update
                name: NextUpdt
                icon: mdi:update
         
          - type: glance
            column_width: 20%
            entities:
              - entity: sensor.lillian_iphone_waze_distance
                name: WazeDist
                icon: mdi:map-marker-distance
              - entity: sensor.lillian_iphone_calc_distance
                name: CalcDist
                icon: mdi:map-marker-distance
              - entity: sensor.lillian_iphone_dir_of_travel
                name: Direction
                icon: mdi:compass-outline
              - entity: sensor.lillian_iphone_last_located
                name: Located
                icon: mdi:map-clock
              - entity: sensor.lillian_iphone_last_update
                name: LastUpdt
                icon: mdi:history
          - type: entities
            entities:
              - entity: sensor.lillian_iphone_info
                name: Info
                icon: mdi:information-outline 

#=============================================================
  - title: iCloud Event Log
    icon: mdi:information-outline 
    cards: 
      - type: custom:icloud3-event-log-card
        entity: sensor.icloud3_event_log

#============================================================= 
  - title: iCloud Commands
    icon: mdi:cloud-upload-outline
    cards: 
      - type: entities
        title: iCloud3 Device Tracker Commands
        show_header_toggle: false
        entities:
          - script.icloud_command_resume_polling
          - script.icloud_command_pause_polling
          - script.icloud_command_restart
          - script.icloud_restart_service
          - type: divider
          - script.icloud_set_interval_30_sec
          - script.icloud_set_interval_1_min
          - script.icloud_set_interval_5_min
          - script.icloud_set_interval_15_min
          - script.icloud_set_interval_30_min
          - script.icloud_set_interval_45_min
          - script.icloud_set_interval_1_hrs
          - script.icloud_set_interval_90_mins
          - script.icloud_set_interval_5_hrs
          - type: divider
          - script.icloud_command_toggle_icloud_disabled
          - script.icloud_command_toggle_waze
          - script.icloud_command_reset_waze_range
          - script.icloud_lost_iphone_invalid
          - script.icloud_update_location
          
      - type: entities
        title: iCloud3 Commands - Gary
        show_header_toggle: false
        entities:   
          - script.icloud_command_resume_polling_gary
          - script.icloud_command_pause_polling_gary
          - script.icloud_set_interval_2_min_gary
          - script.icloud_set_interval_10_min_gary
          - script.icloud_set_interval_1_min_lillian
          - script.icloud_set_interval_10_min_lillian
          - script.icloud_update_location_gary
          - script.icloud_lost_iphone_gary
          
      - type: entities
        title: iCloud3 Service Calls
        show_header_toggle: false
        entities:    
          - script.icloud_lost_iphone_lillian
          - script.icloud_lost_iwatch_lillian
          - script.icloud_gary_iphone_see_away
          - script.icloud_update_location_lillian
         
